#!/usr/bin/env python3
"""
Shared async REPL for Klea chat interfaces.

File: klea_utils/ui/tui/repl.py

Copyright 2026 Ankur Sinha
Author: Ankur Sinha <sanjay DOT ankur AT gmail DOT com>
"""

import json
import logging
import uuid

logger = logging.getLogger(__name__)


async def run_repl(
    url: str,
    title: str,
    single_query: str = "",
    app_prefix: str = "klea",
) -> None:
    """Run an interactive or single-query chat REPL.

    Connects to the API server's SSE ``/query/stream`` endpoint and
    displays progress labels and the final answer.

    In interactive mode each query is sent as the user types it;
    the REPL does not batch queries.

    :param url: Base URL of the API server (e.g. ``http://127.0.0.1:8005``)
    :param title: Application title displayed on start
    :param single_query: If set, run one query and exit instead of REPL loop
    :param app_prefix: Prefix for user/assistant labels (e.g. ``"klea"``)
    """
    # Lazy: avoids importing httpx + yaspin (and their deps) at module level
    import httpx
    from yaspin import yaspin

    from klea_utils.api.utils import check_api_is_ready

    session_id = str(uuid.uuid4())

    with yaspin(text="Waiting for API..."):
        await check_api_is_ready(f"{url}/health/ready")

    async def _query_one(query: str) -> None:
        full_response = ""
        error_msg = ""
        print()

        with yaspin(text="Working ...", timer=True) as spinner:
            async with httpx.AsyncClient(timeout=None) as client:
                async with client.stream(
                    "POST",
                    f"{url}/query/stream",
                    json={"query": query, "session_id": session_id},
                ) as response:
                    response.raise_for_status()
                    async for line in response.aiter_lines():
                        if not line.startswith("data: "):
                            if line.strip():
                                logger.warning("Skipping non-data line: %s", line[:80])
                            continue
                        event = json.loads(line[6:])  # strip out "data: "
                        if event["type"] == "progress":
                            spinner.text = event["node"]
                        elif event["type"] == "complete":
                            full_response = event.get("message_for_user", "")
                            spinner.ok("[OK]")
                        elif event["type"] == "error":
                            error_msg = event.get("message", "Unknown server error")
                            spinner.fail("[ERROR]")
                            break

        output = error_msg or full_response
        print(f"{app_prefix} (AI) >>> {output}")
        print("\n" + "-" * 40 + "\n")

    if single_query:
        print(f"{app_prefix} (USER) >>> {single_query}")
        await _query_one(single_query)
        return

    print(f"*** {title} ({url}) ***")
    print("Please note that answers are generated by LLMs and may be incorrect.")
    print()
    print("Type 'quit' to exit.")
    print("\n" + "-" * 40 + "\n")

    while True:
        q = input(f"{app_prefix} (USER) >>> ")
        if q.lower() == "quit":
            break
        await _query_one(q)

    print(f"\n{app_prefix} >>> Bye!")
