#!/usr/bin/env python3
"""
Planner node for KleaAgent

File: klea_agent/nodes/planner.py

Copyright 2026 Ankur Sinha
Author: Ankur Sinha <sanjay DOT ankur AT gmail DOT com>
"""

import logging
from typing import Any, ClassVar, override

from klea_utils.llm import extract_llm_output_content, prompt_value_to_messages
from klea_utils.mcp.schemas import ToolInfo
from klea_utils.nodes.abstract import NodeStreamData
from klea_utils.nodes.base import BaseLLMNode
from pydantic import BaseModel

from klea_agent.schemas import PlanSchema


class Planner(BaseLLMNode[PlanSchema]):
    """Node that creates or updates an execution plan.

    Uses the tool descriptions generated by ``BaseLangGraph._build_tools_info``
    (``self._tools_info``) — the orchestrator passes ``tools_info`` via
    ``set_tools_info`` before the graph is compiled.  This keeps the
    available-tools list consistent with ``ToolsPicker`` and the MCP registry.
    """

    model_type = "plan"
    model_defaults: ClassVar[dict[str, Any]] = {
        "temperature": 0.01,
        "max_output_tokens": 4096,
    }

    def __init__(
        self,
        logger: logging.Logger,
        label: str,
        llm_models: dict[str, Any],
    ):
        """Initialise the planner node.

        :param logger: Logger instance
        :param label: Human-readable label for UI progress display
        :param llm_models: ``{role: LLMModel}`` dict (from ``BaseLangGraph.llm_models``)
        """
        super().__init__(
            logger=logger,
            label=label,
            llm_models=llm_models,
            output_schema=PlanSchema,
            memory=False,
        )
        self._tools_info: dict[str, dict[str, ToolInfo]] = {}
        self._tools_description = ""

    def _get_tool_descriptions(self) -> str:
        """Return combined tool descriptions from ``_tools_info``.

        Mirrors ``klea_utils/nodes/tools_picker.py:ToolsPicker._get_tool_descriptions``
        but without domain filtering — the agent's single ``code`` domain
        includes all tools.
        """
        parts = [
            info.description or ""
            for domain_tools in self._tools_info.values()
            for info in domain_tools.values()
        ]
        return "\n\n".join(parts)

    def set_tools_info(self, tools_info: dict[str, dict[str, ToolInfo]]) -> None:
        """Set tool metadata (called by orchestrator after construction).

        Stores the per-domain ``ToolInfo`` map from ``BaseLangGraph.tools_info``
        and refreshes the cached description string.
        """
        self._tools_info = tools_info or {}
        self._tools_description = self._get_tool_descriptions()

    @override
    def _get_prompt_variables(self, state: BaseModel) -> dict:
        """Format prompt with current plan state."""
        return {
            "query": getattr(state, "query", ""),
            "goal": getattr(state, "goal", ""),
            "step_list": getattr(getattr(state, "plan", None), "step_list", []),
            "current_step_index": getattr(
                getattr(state, "plan", None), "current_step_index", 0
            ),
            "artefacts": getattr(state, "artefacts", {}),
            "discovery": getattr(state, "discovery_persistent", {}),
            "observations": getattr(state, "step_outputs", {}),
            "tools_description": self._get_tool_descriptions(),
        }

    @override
    def _update_state(self, result: PlanSchema, state: BaseModel) -> dict[str, Any]:
        """Update plan and generate summary for user."""
        plan_summary = "## Plan summary:\n\n"
        for step in result.step_list:
            plan_summary += f"- {step.step_number}: {step.description}\n"

        plan = state.plan  # type: ignore
        plan.step_list = result.step_list

        return {"plan": plan, "message_for_user": plan_summary}

    @override
    def _get_info(self) -> NodeStreamData:
        """Return plan summary for the inspector."""
        assert self._last_state_updates is not None
        assert self._last_result is not None
        result = self._last_result
        mode = (
            getattr(self._last_state, "mode", "general")
            if self._last_state
            else "general"
        )
        if isinstance(result, PlanSchema):
            summary = (
                f"Plan with {len(result.step_list)} step(s), status={result.status}"
            )
            details = {
                "step_count": len(result.step_list),
                "status": result.status,
                "steps": [
                    {"step_number": s.step_number, "description": s.description}
                    for s in result.step_list
                ],
                "mode": mode,
            }
        else:
            summary = "Plan updated"
            details: dict[str, Any] = {"mode": mode}
        return NodeStreamData(
            heading="Plan",
            summary=summary,
            details=details,
        )

    @override
    def _get_debug(self) -> NodeStreamData:
        """Return info + prompt and raw/processed output."""
        assert self._last_state is not None
        assert self._last_prompt is not None
        assert self._last_output is not None
        assert self._last_result is not None
        info = self._get_info()
        details = info.details.copy()
        details.update(
            {
                "input_prompt": prompt_value_to_messages(self._last_prompt),
                "unprocessed_output": extract_llm_output_content(self._last_output),
                "processed_output": str(self._last_result),
                "tools_description": self._get_tool_descriptions(),
            }
        )
        return NodeStreamData(
            heading=info.heading, summary=info.summary, details=details
        )

    @override
    def _get_default_error_result(self) -> PlanSchema:
        """Return default result when processing fails."""
        return PlanSchema(status="failed")
