#!/usr/bin/env python3
"""
Cli for klea_code.

File: klea_code/ui/cli.py

Copyright 2026 Ankur Sinha
Author: Ankur Sinha <sanjay DOT ankur AT gmail DOT com>
"""

import asyncio
import shlex
import subprocess
import uuid
from contextlib import chdir
from pathlib import Path

import typer
from klea_utils.api.utils import validate_url

code_app = typer.Typer(help="Simple KLEA Code user client (WIP)")


def _validate_url(value: str) -> str:
    try:
        return validate_url(value)
    except ValueError as e:
        raise typer.BadParameter(str(e))


@code_app.command()
def cli(
    server_url: str = typer.Option(
        "http://127.0.0.1:8005",
        "--server",
        "-s",
        help="KLEA Code server (URL:port)",
        callback=_validate_url,
    ),
    single_query: str = typer.Option(
        None, "--single-query", "-q", help="Single query mode: answer a query and exit"
    ),
    title: str = typer.Option(
        "KLEA code", "-title", "-t", help="Title for application"
    ),
):
    """Klea Code cli client"""
    print(f"*** {title} ***")
    print("Please note that answers are generated by LLMs and may be incorrect.")
    print()
    print("Type 'quit' to exit.")
    print()
    print()

    url = server_url

    async def cli_main():
        """Cli main async"""
        # Lazy: avoids importing httpx + klea_utils.api (and their deps)
        # at module level, which would slow down --help.
        import httpx
        from klea_utils.api.utils import check_api_is_ready
        from yaspin import yaspin

        session_id = str(uuid.uuid4())

        with yaspin(text="Waiting for API..."):
            response = await check_api_is_ready(f"{url}/health/ready")

        if len(single_query):
            print(f"klea (USER) >>> {single_query}\n\n")
            if single_query.lower() == "quit":
                pass
            else:
                with yaspin(text="Working ..."):
                    async with httpx.AsyncClient() as client:
                        response = await client.post(
                            f"{url}/query",
                            json={"query": single_query, "session_id": session_id},
                            timeout=None,
                        )
                        response_result = response.json().get("result")
                        print(f"klea (AI) >>> {response_result}\n\n")

        else:
            while (query := input("klea (USER) >>> ")) != "quit":
                # we use checkpoints, so we don't need to store and reload the
                # state ourselves
                with yaspin(text="Working ..."):
                    async with httpx.AsyncClient() as client:
                        response = await client.post(
                            f"{url}/query",
                            json={"query": query, "session_id": session_id},
                            timeout=None,
                        )
                        response_result = response.json().get("result")
                        print(f"klea (AI) >>> {response_result}\n\n")

    try:
        asyncio.run(cli_main())
    except KeyboardInterrupt:
        print("\nInterrupted. Exiting.")

    print("klea >>> Bye!")


@code_app.command()
def web(
    title: str = typer.Option(
        "KLEA Code", "--title", "-t", help="Title for application"
    ),
    server_url: str = typer.Option(
        "http://127.0.0.1:8005",
        "--server",
        "-s",
        help="KLEA Code server URL:port",
        callback=_validate_url,
    ),
):
    """Klea Code Streamlit client"""
    # streamlit app
    cwd = Path(__file__).parent
    with chdir(cwd):
        subprocess.run(
            shlex.split(f"streamlit run streamlit_ui.py '{title}' '{server_url}'")
        )


if __name__ == "__main__":
    code_app()
